### ISSUE TITLE
ArgumentError (unknown SSL method `TLSv1_2'.)

### ISSUE THREAD

**Issue by dimanyc** [paypal/adaptivepayments-sdk-ruby#25]
Hi,

I'm running `paypal-sdk-adaptivepayments (1.117.1)` on a Win system. After I make the api call with:
```ruby
 response = api.pay(pay)  
```

I get:
```
 ArgumentError (unknown SSL method `TLSv1_2'.):
 ```

**Comment by bluk** [comment]
Are you using a Ruby runtime >= 2.0.0? Ruby >= 2.0.0 is required due to a TLS v1.2 requirement for connecting to PayPal's API servers (only sandbox for now but soon live production systems as well).

For more information, you can try the [PayPal TLS Update repository](https://github.com/paypal/TLS-update#ruby) which has links to the official microsites for the dates and other information.
